-- Admin users table for login (use with DATABASE_URL / postgres.js).
-- Run this in your Supabase SQL editor or via psql.

CREATE TABLE IF NOT EXISTS admin_users (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email      TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_users_email ON admin_users (email);

-- Optional: insert first admin (replace the hash with one generated by your app).
-- Example using bcrypt (run in Node): require('bcryptjs').hashSync('AfrESH2026@Rev', 10)
